Update python-package.yml

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -39,7 +39,13 @@ jobs:
       run: |
         poetry add pylint
         # stop the build if there are Python syntax errors or undefined names
-        poetry run pylint mtbl_playerkit/ --max-line-length=127
+        poetry run pylint mtbl_playerkit/ --max-line-length=127 || exit_code=$?
+
+        # Exit codes 1, 2 indicate fatal/error messages
+        if [ $exit_code -eq 1 ] || [ $exit_code -eq 2 ]; then
+            exit $exit_code
+        fi
+        
         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
 
     - name: Test with pytest & coverage
